### ISSUE TITLE
Vom Server gekickt

### ISSUE THREAD

**Issue by ghost** [Ste3et/furniture#11]
Mein wenn ich den Crossbow setzen will werde ich vom Server gekickt. Im log steht leider keine Fehlermeldung, aber ich habe hier einen Screenshot vom Client.
![error](https://cloud.githubusercontent.com/assets/17518878/13961223/edc38c7a-f05b-11e5-9151-9e732b87d7fe.PNG)

**Comment by Ste3et** [comment]
Update dein Portocollib zu #266
