### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghost** [Ste3et/furniture#24]
normal logs
http://pastebin.com/jLtDq0BR

timings
https://timings.aikar.co/v2/?id=774c786a48f94894a81ebc641a359fbc

crash logs
http://pastebin.com/P28ZtG9h

files
[files.zip](https://github.com/Ste3et/furniture/files/403188/files.zip)

**Comment by Ste3et** [comment]
Your plugins\FurnitureLib\limitation\chunk.yml is wrong configurated use the yaml Parser online Tool to fix this.
