### ISSUE TITLE
Could not pass event FurnitureClickEvent to DiceFurniture v3.0

### ISSUE THREAD

**Issue by aurel85** [Ste3et/furniture#26]
Hey,

Since the switch to 1.11 it happens that at the reboot (or not sometimes) of my server the file furniture.db is not recognized on the server, basically all furnitures have disappeared IG. Yet in the console no error message at that time and the file was not reset. The file can not be put back on the server, it is corrupted.

By cons, from time to time I find this error message in my console related plugins Furnitures :

http://pastebin.com/cycVyWjQ

Note that I suppressed Light API and I use ProtocolLib more the other necessary dependencies.

**Comment by Ste3et** [comment]
This is a Paperspigot exclusiv bug i hope i can fix it.
