### ISSUE TITLE
[BUG} /furniture give - Does not work in console 

### ISSUE THREAD

**Issue by BiGUNMAN** [Ste3et/furniture#27]
I'm using the most updated versions of each of the plugins (ProtectionLib and DiceFurniture). I get the following issue when trying to give a player a piece of furniture via the console. I'm using PaperSpigot 1.10.2

http://i.imgur.com/8ujUJjq.png

**Comment by Ste3et** [comment]
Look at the commands page: http://dicecraft.de/furniture/cmdperm.php you command is wrong or is your player Name Bed ?

**Comment by BiGUNMAN** [comment]
I have no idea, but it works now. I may have made a dumb mistake.
