### ISSUE TITLE
add recipe gui

### ISSUE THREAD

**Issue by ghost** [Ste3et/furniture#29]
you can add new command to list all recipe in gui
/furniture recipegui

![2017-05-01_17 46 06](https://cloud.githubusercontent.com/assets/5884000/25584463/641a115e-2e96-11e7-999e-b437271afd00.png)
![2017-05-01_17 49 09](https://cloud.githubusercontent.com/assets/5884000/25584501/888252fe-2e96-11e7-8eaf-272942a522de.png)

**Comment by Ste3et** [comment]
no.

**Comment by Ste3et** [comment]
use the /furniture list command to open a recipe it have the same Overview of all furniture and i think this look 🤢
