### ISSUE TITLE
Flower pot items disappear & Sit error

### ISSUE THREAD

**Issue by OpalMoonstride** [Ste3et/furniture#39]
The items inside furniture, such as the flowers / saplings inside flower pots, are disappearing after a restart. 

Players cannot sit in some furniture, such as chairs. 
I have this error whenever a chair is clicked: https://pastebin.com/khAaLZRH

I am not sure if the problems are related.

CMI: 8.3.3.0
Paper Spigot 1.13.2
Vault 1.6.7

**Comment by Ste3et** [comment]
please use the newest version of protectionlib https://dicecraft.de/furniture/download.php

**Comment by OpalMoonstride** [comment]
Oh, okay! I was using the ProtocolLib linked on your DiceFurniture page. https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/

I installed the latest ProtocolLib, which you have linked. I do not see the error, anymore, but the items in the "Flower Pot"s still disappear on restart. :(

![image](https://user-images.githubusercontent.com/39387146/51053076-9defbe80-15a6-11e9-92de-1df72059dee3.png)

Also, I have "Interact allow" for my world guard region, and I have "Interact" set to allow on my furniture, but normal players cannot interact with furniture.
![image](https://user-images.githubusercontent.com/39387146/51053203-0474dc80-15a7-11e9-939c-d4fd952ccdb2.png)
![image](https://user-images.githubusercontent.com/39387146/51053288-3dad4c80-15a7-11e9-8601-1877731101b4.png)
