### ISSUE TITLE
Chunk unload when you sit on forniture

### ISSUE THREAD

**Issue by Malachiel87** [Ste3et/furniture#41]
I noticed almost all forniture that allow player to sit, when you sit on these, it unload all chunks around, and stay like this until that player join, there are no  relevant errors about this.
Using 1.13.2 paperspigot and latest protocolprotection, and furniture/dicefurniture. Using TornToiletA (from model site) it happen at 99% of times when you try to sit on it

**Comment by Ste3et** [comment]
The problem is not the furnitureLib the problem is the barrier block from the toilet this is a minecraft vanilla bug you glitched out of the block here is a little fix https://my.hidrive.com/lnk/lG4OWnNk

**Comment by Malachiel87** [comment]
so you fixed using a flower pot instead barrier?

**Comment by Ste3et** [comment]
yea :D it have a little hitbox instand the big hitbox of the barrier block
