### ISSUE TITLE
Console Errors (Error occurred while disabling FurnitureLib v2.2.7)

### ISSUE THREAD

**Issue by BboyZeroOne** [Ste3et/furniture#49]
Long ass console error. Not too sure what is it about, I have dicefurniture and all its dependencies on the latest version on paperspigot 1.15.2 (328)

https://pastebin.com/0GYb797Q

**Comment by BboyZeroOne** [comment]
Why is this ticket closed? Any explanation?

**Comment by Ste3et** [comment]
Sure the Furniture repo didn't work with any kind of Database structure and the error is a duplicate of: https://github.com/Ste3et/FurnitureLib/issues/62
