### ISSUE TITLE
Can't interact with bench after update to 1.16.4

### ISSUE THREAD

**Issue by imparium-de** [Ste3et/furniture#52]
Title says it all. The console doesn't show any errors. 
Small video that shows the problem: https://streamable.com/oqydka
In spectator mode you can see the armor stands but when trying to remove them via command `/kill @e[distance=1]`, it says "No entity was found". Is there another way to get rid of the "ghost bench"? :D

MC version: 1.16.4 
This server is running Paper version git-Paper-261 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
Previous version: git-Paper-375 (MC: 1.15.2)

FurnitureLib 2.3.6
DiceFurniture 3.4.6

**Comment by Ste3et** [comment]
Please provide your complete latest.log after rightclick the model!

**Comment by Ste3et** [comment]
Is it possible that you change the file name from the model?
These generate the Ghost Models for myself, you can remove it simple with "/furniture remove project:JB-Parkbank1"

**Comment by imparium-de** [comment]
Sorry for the late reply. No we didn't rename the model.
Here's the log: [latest.log](https://github.com/Ste3et/furniture/files/5564592/latest.log)
The command you provided works flawlessly, thanks!

**Comment by Ste3et** [comment]
I way to reproduce that bug would be releay usefull.
Du kannst auch auf deutsch schreiben 👍

**Comment by imparium-de** [comment]
Alles klar :D Habe es mir nur angewöhnt auf Englisch zu schreiben damit Leute mit ähnlichen Problemen die kein Deutsch sprechen auch an Diskussionen teilnehmen können ^^

Also wir haben noch ein paar Modelle aufm Server die verbugged und nicht replaced worden sind, an denen könnte man noch ein wenig experimentieren. Komischerweise sind es nicht alle Modelle. Der "BarStool" funktioniert nach wie vor, aber die Armor Stands von Dingen wie der "KEMicrowaveA" und dem "KEOvenA" brennen einfach :D https://i.imgur.com/7dkyiOz.png 

Wenn du möchtest kannst du mich auf Discord adden `derMiepz#5898`, dann kannst du dir das selber mal anschauen. ^^

**Comment by Ste3et** [comment]
Sorry für die späte Antwort, ich bin derzeit beruflich ziemlich im Stress, das Problem konnte lokalisiert werden, eine einfache Lösung für das Problem hab ich allerdings momentan nicht, es liegt an einem alten Code der in der Vergangenheit miserabel umgesetzt wurde und vor 1-2 Updates korrigiert wurde, anscheinend gibt es einen Version Problem zwischen FurnitureLib 2.3.6 und der älteren Versionen, dadurch wird bei allen alten platzierten Modelle die Marker Metadata falsch interpretiert.

Eine schnelle Lösung wäre natürlich alle Modelle erneut zu platzieren, das ist natürlich nicht der way to go, derzeit kann ich allerdings nicht anders helfen, ich werde mich mal am Wochenende an das Problem setzen, da ich leider wieder am Montag zurück auf Montage ins Ausland muss kann ich nicht versprechen das es so schnell ne Lösung geben wird.

**Comment by imparium-de** [comment]
Kein Problem, hauptsache man weiß woran es liegt ^^
Wir haben zum Glück nicht all zu viele Models die aktiv genutzt werden, darum hält sich der Schaden ziemlich in Grenzen. Sobald du eine Version hast die den Fehler beheben soll helfen wir natürlich gerne weiter und werden sie testen. :D

**Comment by Ste3et** [comment]
Probier bitte mal das Aktuelle Update von spigotmc.org sort ist auch ein Kommando enthalten zum beheben bereits platzierter Modelle/furniture debug fixmodel

**Comment by imparium-de** [comment]
Hat leider nicht ganz funktioniert. Ich hatte die beiden Parkbänke ja mit `/furniture remove project:JB-Parkbank1` entfernt, danach war alles normal. Jetzt, trotz `/furniture debug fixmodel` ist die Bank noch kaputt.

Damals waren auch noch die "WoodLazyChair" und "KEBeachChair" kaputt, die hatte ich dann direkt mit ausgetauscht. Andere Modelle hingegen wie die "Hammok" waren direkt nach dem Ersetzen der neuen .jar Dateien gefixt. Außerdem hab ich noch zwei kleine Rechtschreibfehler gefunden.
`Please enter these command to confirm it: '/furniture debug fixmodel XXXX' ho have 60 secounds`
"this" anstatt "these" und 
"you" anstatt "ho"

https://streamable.com/mo5ckt

**Comment by imparium-de** [comment]
Ach und das ist mir eben erst aufgefallen. Ich weiß nicht ob das dazu gehört, aber ich glaube auch die Meldung hier ist neu ^^ https://pastebin.com/M0Wkbw7a

**Comment by Ste3et** [comment]
Probiere mal bitte diese DEV Build Version -> https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.9.x%20-%201.16.x&buildNummer=225481663

**Comment by imparium-de** [comment]
Habe ich gemacht, aber hat leider nicht funktioniert. :(

**Comment by Ste3et** [comment]
Was heißt leider nicht funkltioniert?

**Comment by imparium-de** [comment]
Command wurde ausgeführt und man kann nach wie vor nicht mit ihnen interagieren.
