### ISSUE TITLE
[suggestion]GriefDefender Support

### ISSUE THREAD

**Issue by hkkongou** [Ste3et/furniture#56]
ProtectionLib support a lot of claim plugins, but does not support griefdefender, players can place dicefurniture furniture inside griefdefender claims without any prevention.

Please add Griefdefender support so that players cannot place furniture in places does not belongs to them. Thank you.

*Griefdefender is not same as griefprevention

**Comment by Ste3et** [comment]
Thank you for your suggestion, i can't add support for https://www.spigotmc.org/resources/1-8-8-1-16-5-griefdefender.68900/ becouse it is a premium plugin, and he didn't obtain an free developer version to use they artifact to build a protectionlib!

**Comment by ahdg6** [comment]
GD is a open-source plugin.
Source:https://github.com/bloodmc/Griefdefender
You can get API in this repo https://github.com/bloodmc/GriefdefenderAPI

**Comment by Ste3et** [comment]
Yea the repo is public but i didn't have an maven artifact to work with

**Comment by Ste3et** [comment]
Nevermind Griefdefender is on jitpack https://jitpack.io/#bloodmc/GriefdefenderAPI

**Comment by Ste3et** [comment]
Id think the devbuild in my discussion should work https://github.com/Ste3et/ProtectionLib/issues/6

**Comment by hkkongou** [comment]
> Id think the devbuild in my discussion should work [Ste3et/ProtectionLib#6](https://github.com/Ste3et/ProtectionLib/issues/6)

it work great, thank you so much
but is it possible to show an extra message when the place event is cancelled?
