### ISSUE TITLE
Geysermc/bedrock support?

### ISSUE THREAD

**Issue by WongIong** [Ste3et/furniture#57]
Is it possible to make this furniture plugin works on bedrock version?
people can only see things like this
![image](https://user-images.githubusercontent.com/36799194/134976584-3559dbe2-34df-4f74-80da-1dbc6295a50d.png)
but it should be like this
![image](https://user-images.githubusercontent.com/36799194/134976570-7dfb3141-d2c4-48dc-b916-e61710d12527.png)

**Comment by Ste3et** [comment]
Its technical not possible, because badrock didn't provide the option to roatete bodyparts of armorstands

**Comment by WongIong** [comment]
okay, thank you anyways
