### ISSUE TITLE
How to allow other players without op to sit on the furniture?

### ISSUE THREAD

**Issue by RedixWasTaken** [Ste3et/furniture#59]
How do I allow other people to sit on furniture because I've been looking everywhere and I can't find it anywhere? Do you need op to sit on furniture or is there a command?

**Comment by Ste3et** [comment]
Take a look on the permission Page https://dicecraft.de/furniture/newPerms.php

**Comment by RedixWasTaken** [comment]
How can I do these commands tho? For Example furniture.player

**Comment by Ste3et** [comment]
you need an permission Plugin like https://www.spigotmc.org/resources/luckperms.28140/ for that

**Comment by RedixWasTaken** [comment]
I'm still confused how do you get that to work? It's like I need a bunch of code and scripts to get this to work. Just to make one simple command.

**Comment by Ste3et** [comment]
Please learn something about permissions https://luckperms.net/wiki/Home that is a simple common system and have nothing to do with my plugins.
Each other public plugins use the same system!
